#!/bin/bash

FLIF="./flif -vvv"
TMPDIR="tmp_raw2flif"

if [ $# -lt 2 ]
then
    echo "Usage: $0  input_raw_file  output.rggb"
else
    mkdir -p $TMPDIR
    rm -f $TMPDIR/*
    if dcraw -i "$1" > /dev/null
    then
        # get Filter pattern //Fuji_xf1: BGGRBGGRBGGRBGGR, Pana_gh3: GBRGGBRGGBRGGBRG, leica_m82: RGGBRGGBRGGBRGGB
        CFAPattern=`dcraw -i -v "$1" | grep "Filter pattern: " | sed "s/Filter pattern: //g"`
        # get Orientation: "Horizontal (normal)", "Rotate 90 CW", "Rotate 180 CW", "Rotate 270 CW"
	Orientation=`exiftool -Orientation "$1" | sed "s/Orientation                     : //g"`
	case "$CFAPattern" in
		RGGBRGGBRGGBRGGB)
			case "$Orientation" in
				"Horizontal (normal)")
					CFAPattern="RGGB";;
				"Rotate 90 CW")
					CFAPattern="GRBG";;
				"Rotate 180 CW")
					CFAPattern="BGGR";;
				"Rotate 270 CW")
					CFAPattern="GBRG";;
				*)
					echo "This orientation is unknown: $Orientation"
					exit 1
			esac;;
		GRBGGRBGGRBGGRBG)
			case "$Orientation" in
				"Horizontal (normal)")
					CFAPattern="GRBG";;
				"Rotate 90 CW")
					CFAPattern="BGGR";;
				"Rotate 180 CW")
					CFAPattern="GBRG";;
				"Rotate 270 CW")
					CFAPattern="RGGB";;
				*)
					echo "This orientation is unknown: $Orientation"
					exit 1
			esac;;
		BGGRBGGRBGGRBGGR)
			case "$Orientation" in
				"Horizontal (normal)")
					CFAPattern="BGGR";;
				"Rotate 90 CW")
					CFAPattern="GBRG";;
				"Rotate 180 CW")
					CFAPattern="RGGB";;
				"Rotate 270 CW")
					CFAPattern="GRBG";;
				*)
					echo "This orientation is unknown: $Orientation"
					exit 1
			esac;;
		GBRGGBRGGBRGGBRG)
			case "$Orientation" in
				"Horizontal (normal)")
					CFAPattern="GBRG";;
				"Rotate 90 CW")
					CFAPattern="RGGB";;
				"Rotate 180 CW")
					CFAPattern="GRBG";;
				"Rotate 270 CW")
					CFAPattern="BGGR";;
				*)
					echo "This orientation is unknown: $Orientation"
					exit 1
			esac;;
		*)
			echo "This pattern is unknown: $CFAPattern"
			exit 1
	esac
	# TODO: Remove this case part when FLIF can handle the "CFAPattern" comment
	case "$CFAPattern" in
		RGGB)
			Rotate="";;
		GRBG)
			Rotate="-t 5";;
		BGGR)
			Rotate="-t 3";;
		GBRG)
			Rotate="-t 6";;
		*)
			echo "This pattern is unknown: $CFAPattern"
			exit 1
	esac
	# Add CFAPattern comment
	echo "# CFAPattern: $CFAPattern" > "$2"	
        # extract raw data, presumably in some kind of RGGB format
        dcraw -E -4 -c $Rotate "$1" >> "$2"
    else
        echo "Not a camera raw file: $1"
    fi
    rm -f $TMPDIR/*
    rmdir $TMPDIR
fi
